# This Docker image is based on Step 2 in "Dockerfile", with some steps removed
# as they will be performed in the Dockerfiles that use this image
# (Dockerfile.dev, Dockerfile.dev-additions)
ARG JDK_VERSION=17

FROM docker.io/eclipse-temurin:${JDK_VERSION} AS ant_build
# Install Apache Ant
RUN apt-get update \
    && apt-get install -y --no-install-recommends ant \
    && apt-get purge -y --auto-remove \
    && rm -rf /var/lib/apt/lists/*
