# UMD-provided file running DSpace as part of a "Quick Build" setup
# This file is based on "Dockerfile.dev"

# This Dockerfile uses JDK17 by default.
# To build with other versions, use "--build-arg JDK_VERSION=[value]"
ARG JDK_VERSION=17
# The Docker version tag to build from
ARG DSPACE_VERSION=8_x-dev-base
# The Docker registry to use for DSpace images. Defaults to "docker.io"
# NOTE: non-DSpace images are hardcoded to use "docker.io" and are not impacted by this build argument
ARG DOCKER_REGISTRY=docker.io

# Step 1 - Run Maven Build
# UMD Customization
FROM docker.lib.umd.edu/mdsoar:${DSPACE_VERSION} AS build
# End UMD Customization
ARG TARGET_DIR=dspace-installer
WORKDIR /app

USER dspace

# UMD Customization
# Copy the DSpace source code from the /dspace/modules/[additions]|[server]
# directories from the local machine) into the workdir
# (excluding .dockerignore contents)
RUN rm -rf /app/dspace/modules/additions /app/dspace/modules/server
ADD --chown=dspace dspace/modules/additions /app/dspace/modules/additions
ADD --chown=dspace dspace/modules/server /app/dspace/modules/server
# End UMD Customization

# Copy the dspace-installer directory to /install.  Clean up the build to keep the docker image small
# Maven flags here ensure that we skip building test environment and skip all code verification checks.
# These flags speed up this compilation as much as reasonably possible.
ENV MAVEN_FLAGS="-P-test-environment -Denforcer.skip=true -Dcheckstyle.skip=true -Dlicense.skip=true -Dxml.skip=true"
# UMD Customization
RUN mvn package -rf org.dspace:modules -pl '!org.dspace:dspace-iiif,!org.dspace:dspace-oai,!org.dspace:dspace-rdf,!org.dspace:dspace-sword,!org.dspace:dspace-swordv2' ${MAVEN_FLAGS} && \
# End UMD Customization
  mv /app/dspace/target/${TARGET_DIR}/* /install && \
  mvn clean
# Remove the server webapp to keep image small.
RUN rm -rf /install/webapps/server/

# Step 2 - Run Ant Deploy
# UMD Customization
FROM docker.lib.umd.edu/mdsoar-ant:latest AS ant_build
# End UMD Customization
ARG TARGET_DIR=dspace-installer
# COPY the /install directory from 'build' container to /dspace-src in this container
COPY --from=build /install /dspace-src
WORKDIR /dspace-src

# UMD Customization
# Ant is installed as part of the "mdsoar-ant" Docker image
# End UMD Customization

# Run necessary 'ant' deploy scripts
RUN ant init_installation update_configs update_code update_webapps

# Step 3 - Start up DSpace via Runnable JAR
FROM docker.io/eclipse-temurin:${JDK_VERSION}
# Below syntax may look odd, but it is how to override dspace.cfg settings via env variables.
# See https://github.com/DSpace/DSpace/blob/main/dspace/config/config-definition.xml
# "dspace__P__dir" is setting the value of the "dspace.dir" configuration. This is our installation directory.
ENV dspace__P__dir=/dspace
# Copy the /dspace directory from 'ant_build' container to /dspace in this container
COPY --from=ant_build /dspace $dspace__P__dir
WORKDIR $dspace__P__dir
# Need host command for "[dspace]/bin/make-handle-config"
# UMD Customization
# Commenting out, because no need for "make-handle-config" in dev environment
# RUN apt-get update \
#     && apt-get install -y --no-install-recommends host \
#     && apt-get purge -y --auto-remove \
#     && rm -rf /var/lib/apt/lists/*
# End UMD Customization
# Expose Tomcat port (8080) & Handle Server HTTP port (8000)
EXPOSE 8080 8000
# Give java extra memory (2GB)
ENV JAVA_OPTS=-Xmx2000m

# UMD Customization
ENV TZ=America/New_York
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        csh \
        libgetopt-complete-perl \
        libconfig-properties-perl
# End UMD Customization
# On startup, run DSpace Runnable JAR (uses the "dspace.dir" setting defined in "dspace__P__dir" env variable)
ENTRYPOINT ["java", "-jar", "webapps/server-boot.jar"]
