FROM solr:9.8.1

COPY --chown=solr ./search /opt/solr/server/solr/configsets/search
COPY --chown=solr ./statistics /opt/solr/server/solr/configsets/statistics
COPY --chown=solr ./oai /opt/solr/server/solr/configsets/oai
